### ISSUE TITLE
Add instructions to generate the CSV file

### ISSUE THREAD

**Issue by balogic** [Dineshkarthik/OSM-Translate-TelegramBot#15]
It would be nice if instructions to generate CSV file is added. Also, Is there a way to extract those details from the OpenStreetMap? Currently, I need to manually add nodes and Location.

**Comment by tshrinivasan** [comment]
here are some notes by Srikanth logic
http://telegra.ph/OSM-data-extraction-for-translation-10-09

**Comment by balogic** [comment]
Thanks. Will check it.
