### ISSUE TITLE
Export as same bactch as import

### ISSUE THREAD

**Issue by tshrinivasan** [Dineshkarthik/OSM-Translate-TelegramBot#19]
we import strings as many batches.
But current export script, exports them all.

Cant get the recent batch of strings only on export.

Will be nice, if we have options to mention full-export or last batch export.

**Comment by Dineshkarthik** [comment]
As you already have a working db please run the following sql queries in your db before exporting data,

```
ALTER TABLE `translation` ADD COLUMN `is_exported` BIGINT(20) NULL;
UPDATE `translation` SET `is_exported`='0';
```
Also check `README` regarding the update in Config file
