### ISSUE TITLE
On leaderboard, show the counts 

### ISSUE THREAD

**Issue by tshrinivasan** [Dineshkarthik/OSM-Translate-TelegramBot#21]
On leaderboard, show the counts of user's contributions list

**Comment by Dineshkarthik** [comment]
* Add admin users telegram username in config - bot_admin
* To Update Admin users run `python -c 'from populate_db import add_admin; add_admin()'`
* Admin users can use `/broadcast` to broadcast a message to all users using the bot

Considering you already have a production db, run the following sql query:
`ALTER TABLE `users` ADD COLUMN `is_admin` INT NULL DEFAULT 0;`

**Comment by tshrinivasan** [comment]
Display as

username, count

**Comment by Dineshkarthik** [comment]
Fixed.
